"""Admin dashboard HTML pages (split GET routes under /admin/*)."""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import RedirectResponse

from .. import impl_state as _s
from .admin_dashboard_context import build_admin_dashboard_template_context
from .admin_paths import (
    ADMIN_PATH_DASHBOARD,
    ADMIN_PATH_SETTINGS,
    ADMIN_PATH_TRAINING,
    ADMIN_PATH_USERS,
)


def _admin_dashboard_get(
    *,
    request: _s.Request,
    template_name: str,
    admin_list_path: str,
    msg: str | None = None,
    room_sort: str = "id_asc",
    public_user_q: str = "",
    public_user_status: str = "active",
    public_user_verified: str = "all",
    public_user_page: int = 1,
    trash_page: int = 1,
    trash_q: str = "",
    sessions_page: int = 1,
    payments_page: int = 1,
    audit_event_type: str = "",
    audit_status: str = "",
    audit_email: str = "",
    audit_ip: str = "",
    audit_page: int = 1,
    payment_date_from: str = "",
    payment_date_to: str = "",
    post_edit: int = 0,
    center_posts_page: int = 1,
    training_muscle: str = "core",
    training_client_q: str = "",
    training_client_id: int = 0,
    training_tab: str = "assignments",
    training_plan_view: str = "current",
    db: _s.Session,
):
    user, redirect = _s._require_admin_user_or_redirect(request, db)
    if redirect:
        return redirect
    assert user is not None
    return _s.templates.TemplateResponse(
        request,
        template_name,
        build_admin_dashboard_template_context(
            db=db,
            user=user,
            msg=msg,
            room_sort=room_sort,
            public_user_q=public_user_q,
            public_user_status=public_user_status,
            public_user_verified=public_user_verified,
            public_user_page=public_user_page,
            trash_page=trash_page,
            trash_q=trash_q,
            sessions_page=sessions_page,
            payments_page=payments_page,
            audit_event_type=audit_event_type,
            audit_status=audit_status,
            audit_email=audit_email,
            audit_ip=audit_ip,
            audit_page=audit_page,
            payment_date_from=payment_date_from,
            payment_date_to=payment_date_to,
            post_edit=post_edit,
            center_posts_page=center_posts_page,
            training_muscle=training_muscle,
            training_client_q=training_client_q,
            training_client_id=training_client_id,
            training_tab=training_tab,
            training_plan_view=training_plan_view,
            admin_list_path=admin_list_path,
        ),
    )


def register_admin_dashboard_routes(router: APIRouter) -> None:
    """Large dashboard view split across /admin/dashboard, /admin/users, etc."""

    @router.get("/admin", response_class=_s.HTMLResponse)
    def admin_root_redirect():
        return RedirectResponse(url=ADMIN_PATH_DASHBOARD, status_code=307)

    @router.get("/admin/dashboard", response_class=_s.HTMLResponse)
    def admin_dashboard_page(
        request: _s.Request,
        msg: str | None = None,
        room_sort: str = "id_asc",
        public_user_q: str = "",
        public_user_status: str = "active",
        public_user_verified: str = "all",
        public_user_page: int = 1,
        trash_page: int = 1,
        trash_q: str = "",
        sessions_page: int = 1,
        payments_page: int = 1,
        audit_event_type: str = "",
        audit_status: str = "",
        audit_email: str = "",
        audit_ip: str = "",
        audit_page: int = 1,
        payment_date_from: str = "",
        payment_date_to: str = "",
        post_edit: int = 0,
        center_posts_page: int = 1,
        training_muscle: str = "core",
        training_client_q: str = "",
        training_client_id: int = 0,
        training_tab: str = "assignments",
        training_plan_view: str = "current",
        db: _s.Session = _s.Depends(_s.get_db),
    ):
        return _admin_dashboard_get(
            request=request,
            template_name="admin_dashboard.html",
            admin_list_path=ADMIN_PATH_DASHBOARD,
            msg=msg,
            room_sort=room_sort,
            public_user_q=public_user_q,
            public_user_status=public_user_status,
            public_user_verified=public_user_verified,
            public_user_page=public_user_page,
            trash_page=trash_page,
            trash_q=trash_q,
            sessions_page=sessions_page,
            payments_page=payments_page,
            audit_event_type=audit_event_type,
            audit_status=audit_status,
            audit_email=audit_email,
            audit_ip=audit_ip,
            audit_page=audit_page,
            payment_date_from=payment_date_from,
            payment_date_to=payment_date_to,
            post_edit=post_edit,
            center_posts_page=center_posts_page,
            training_muscle=training_muscle,
            training_client_q=training_client_q,
            training_client_id=training_client_id,
            training_tab=training_tab,
            training_plan_view=training_plan_view,
            db=db,
        )

    @router.get("/admin/users", response_class=_s.HTMLResponse)
    def admin_users_page(
        request: _s.Request,
        msg: str | None = None,
        room_sort: str = "id_asc",
        public_user_q: str = "",
        public_user_status: str = "active",
        public_user_verified: str = "all",
        public_user_page: int = 1,
        trash_page: int = 1,
        trash_q: str = "",
        sessions_page: int = 1,
        payments_page: int = 1,
        audit_event_type: str = "",
        audit_status: str = "",
        audit_email: str = "",
        audit_ip: str = "",
        audit_page: int = 1,
        payment_date_from: str = "",
        payment_date_to: str = "",
        post_edit: int = 0,
        center_posts_page: int = 1,
        training_muscle: str = "core",
        training_client_q: str = "",
        training_client_id: int = 0,
        training_tab: str = "assignments",
        training_plan_view: str = "current",
        db: _s.Session = _s.Depends(_s.get_db),
    ):
        return _admin_dashboard_get(
            request=request,
            template_name="admin_users.html",
            admin_list_path=ADMIN_PATH_USERS,
            msg=msg,
            room_sort=room_sort,
            public_user_q=public_user_q,
            public_user_status=public_user_status,
            public_user_verified=public_user_verified,
            public_user_page=public_user_page,
            trash_page=trash_page,
            trash_q=trash_q,
            sessions_page=sessions_page,
            payments_page=payments_page,
            audit_event_type=audit_event_type,
            audit_status=audit_status,
            audit_email=audit_email,
            audit_ip=audit_ip,
            audit_page=audit_page,
            payment_date_from=payment_date_from,
            payment_date_to=payment_date_to,
            post_edit=post_edit,
            center_posts_page=center_posts_page,
            training_muscle=training_muscle,
            training_client_q=training_client_q,
            training_client_id=training_client_id,
            training_tab=training_tab,
            training_plan_view=training_plan_view,
            db=db,
        )

    @router.get("/admin/training", response_class=_s.HTMLResponse)
    def admin_training_page(
        request: _s.Request,
        msg: str | None = None,
        room_sort: str = "id_asc",
        public_user_q: str = "",
        public_user_status: str = "active",
        public_user_verified: str = "all",
        public_user_page: int = 1,
        trash_page: int = 1,
        trash_q: str = "",
        sessions_page: int = 1,
        payments_page: int = 1,
        audit_event_type: str = "",
        audit_status: str = "",
        audit_email: str = "",
        audit_ip: str = "",
        audit_page: int = 1,
        payment_date_from: str = "",
        payment_date_to: str = "",
        post_edit: int = 0,
        center_posts_page: int = 1,
        training_muscle: str = "core",
        training_client_q: str = "",
        training_client_id: int = 0,
        training_tab: str = "assignments",
        training_plan_view: str = "current",
        db: _s.Session = _s.Depends(_s.get_db),
    ):
        return _admin_dashboard_get(
            request=request,
            template_name="admin_training.html",
            admin_list_path=ADMIN_PATH_TRAINING,
            msg=msg,
            room_sort=room_sort,
            public_user_q=public_user_q,
            public_user_status=public_user_status,
            public_user_verified=public_user_verified,
            public_user_page=public_user_page,
            trash_page=trash_page,
            trash_q=trash_q,
            sessions_page=sessions_page,
            payments_page=payments_page,
            audit_event_type=audit_event_type,
            audit_status=audit_status,
            audit_email=audit_email,
            audit_ip=audit_ip,
            audit_page=audit_page,
            payment_date_from=payment_date_from,
            payment_date_to=payment_date_to,
            post_edit=post_edit,
            center_posts_page=center_posts_page,
            training_muscle=training_muscle,
            training_client_q=training_client_q,
            training_client_id=training_client_id,
            training_tab=training_tab,
            training_plan_view=training_plan_view,
            db=db,
        )

    @router.get("/admin/settings", response_class=_s.HTMLResponse)
    def admin_settings_page(
        request: _s.Request,
        msg: str | None = None,
        room_sort: str = "id_asc",
        public_user_q: str = "",
        public_user_status: str = "active",
        public_user_verified: str = "all",
        public_user_page: int = 1,
        trash_page: int = 1,
        trash_q: str = "",
        sessions_page: int = 1,
        payments_page: int = 1,
        audit_event_type: str = "",
        audit_status: str = "",
        audit_email: str = "",
        audit_ip: str = "",
        audit_page: int = 1,
        payment_date_from: str = "",
        payment_date_to: str = "",
        post_edit: int = 0,
        center_posts_page: int = 1,
        training_muscle: str = "core",
        training_client_q: str = "",
        training_client_id: int = 0,
        training_tab: str = "assignments",
        training_plan_view: str = "current",
        db: _s.Session = _s.Depends(_s.get_db),
    ):
        return _admin_dashboard_get(
            request=request,
            template_name="admin_settings.html",
            admin_list_path=ADMIN_PATH_SETTINGS,
            msg=msg,
            room_sort=room_sort,
            public_user_q=public_user_q,
            public_user_status=public_user_status,
            public_user_verified=public_user_verified,
            public_user_page=public_user_page,
            trash_page=trash_page,
            trash_q=trash_q,
            sessions_page=sessions_page,
            payments_page=payments_page,
            audit_event_type=audit_event_type,
            audit_status=audit_status,
            audit_email=audit_email,
            audit_ip=audit_ip,
            audit_page=audit_page,
            payment_date_from=payment_date_from,
            payment_date_to=payment_date_to,
            post_edit=post_edit,
            center_posts_page=center_posts_page,
            training_muscle=training_muscle,
            training_client_q=training_client_q,
            training_client_id=training_client_id,
            training_tab=training_tab,
            training_plan_view=training_plan_view,
            db=db,
        )

    @router.get("/admin/musclemap", response_class=_s.HTMLResponse)
    def admin_musclemap_fullscreen(
        request: _s.Request,
        training_muscle: str = "core",
        training_client_q: str = "",
        training_client_id: int = 0,
        training_tab: str = "assignments",
        training_plan_view: str = "current",
        training_body_gender: str = "female",
        training_body_side: str = "front",
        db: _s.Session = _s.Depends(_s.get_db),
    ):
        user, redirect = _s._require_admin_user_or_redirect(request, db)
        if redirect:
            return redirect
        assert user is not None
        return _s.templates.TemplateResponse(
            request,
            "admin_musclemap_fullscreen.html",
            {
                "training_selected_muscle": training_muscle,
                "training_client_q": training_client_q,
                "training_client_id": training_client_id,
                "training_tab": training_tab,
                "training_plan_view": training_plan_view,
                "training_body_gender": training_body_gender,
                "training_body_side": training_body_side,
            },
        )
