"""Authentication helpers: passwords, staff/public JWTs, and FastAPI dependencies."""

from .config import (
    APP_ENV,
    JWT_ALGORITHM,
    JWT_EXPIRES_MINUTES,
    JWT_SECRET,
    PUBLIC_ACCOUNT_DELETE_EXPIRES_MINUTES,
    PUBLIC_EMAIL_VERIFY_EXPIRES_MINUTES,
    PUBLIC_EMAIL_VERIFY_FLASH_EXPIRES_MINUTES,
    PUBLIC_JWT_SECRET,
    PUBLIC_PASSWORD_RESET_EXPIRES_MINUTES,
    PUBLIC_SESSION_EXPIRES_MINUTES,
)
from .dependencies import (
    get_current_user,
    get_current_user_cookie_or_bearer,
    http_bearer_optional,
    oauth2_scheme,
    require_any_permission,
    require_any_permission_cookie_or_bearer,
    require_permissions,
    require_permissions_cookie_or_bearer,
    require_roles,
    require_roles_cookie_or_bearer,
)
from .passwords import hash_password, verify_password
from .public_tokens import (
    create_public_access_token,
    create_public_account_delete_token,
    create_public_email_verification_token,
    create_public_email_verify_flash_token,
    create_public_password_reset_token,
    decode_public_account_delete_token,
    decode_public_email_verification_token,
    decode_public_email_verify_flash_token,
    decode_public_password_reset_token,
    get_public_user_from_token_string,
)
from .staff_tokens import (
    create_access_token,
    create_refresh_token,
    get_user_from_refresh_token_string,
    get_user_from_token_string,
)

__all__ = [
    "APP_ENV",
    "JWT_ALGORITHM",
    "JWT_EXPIRES_MINUTES",
    "JWT_SECRET",
    "PUBLIC_ACCOUNT_DELETE_EXPIRES_MINUTES",
    "PUBLIC_EMAIL_VERIFY_EXPIRES_MINUTES",
    "PUBLIC_EMAIL_VERIFY_FLASH_EXPIRES_MINUTES",
    "PUBLIC_JWT_SECRET",
    "PUBLIC_PASSWORD_RESET_EXPIRES_MINUTES",
    "PUBLIC_SESSION_EXPIRES_MINUTES",
    "create_access_token",
    "create_refresh_token",
    "create_public_access_token",
    "create_public_account_delete_token",
    "create_public_email_verification_token",
    "create_public_email_verify_flash_token",
    "create_public_password_reset_token",
    "decode_public_account_delete_token",
    "decode_public_email_verification_token",
    "decode_public_email_verify_flash_token",
    "decode_public_password_reset_token",
    "get_current_user",
    "get_current_user_cookie_or_bearer",
    "get_public_user_from_token_string",
    "get_user_from_token_string",
    "get_user_from_refresh_token_string",
    "hash_password",
    "http_bearer_optional",
    "oauth2_scheme",
    "require_any_permission",
    "require_any_permission_cookie_or_bearer",
    "require_permissions",
    "require_permissions_cookie_or_bearer",
    "require_roles",
    "require_roles_cookie_or_bearer",
    "verify_password",
]
